# Use the official Node.js 14 image as the base image
FROM node:14

# Set the working directory inside the container to /app
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install the dependencies
RUN npm install --only=production

# Copy the rest of the application code to the container
COPY . .

# Expose port 8080 for the application to listen on
EXPOSE 8080

# Start the NestJS application
CMD ["npm", "run", "start"]

