version: '3'

services:
  api:
    build: ./rest_api
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
    networks:
      - app-network
  frontend:
    build: ./front_end
    ports:
      - "80:80"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
